name: CI/CD

on:
  push:
    branches:
      - development-staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the branch name
        id: branch
        run: echo ::set-output name=branch::${{ github.ref }}

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/dpr-api
            git stash
            git checkout development-staging
            git pull origin development-staging
